"""empty message

Revision ID: 41a76cc4e250
Revises: e48f4da9ebde
Create Date: 2020-11-08 11:41:07.367551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a76cc4e250'
down_revision = 'e48f4da9ebde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Locations',
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.String(), nullable=True),
    sa.Column('lng', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('location_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Locations')
    # ### end Alembic commands ###
